def money(v):
    try:v=float(v or 0)
    except:return "Bilinmiyor"
    return f"${v/1_000_000_000:.2f}B" if v>=1_000_000_000 else f"${v/1_000_000:.2f}M" if v>=1_000_000 else f"${v/1_000:.1f}K" if v>=1_000 else f"${v:.2f}"
def build_scan_error(errors):return "❌ HunterElite taraması tamamlanamadı.\n\n"+"\n".join(f"• {e}" for e in (errors or [])[:6])
def build_report(t,a):
    r=a.get("rug") or {}; p=a.get("pump") or {}; e=a.get("elite") or {}; g=a.get("gem") or {}; x=a.get("x100") or {}; pl=a.get("trade_plan") or {}; d=a.get("decision") or {}
    return (f"🛡 HUNTERELITE V5 FINAL\n━━━━━━━━━━━━━━━━━━\n\n🪙 {t.get('name','Bilinmiyor')} ({t.get('symbol','?')})\n⏱ Yaş: {t.get('age_text','Bilinmiyor')}\n\n🛡 RUG RİSKİ {r.get('score',0)}/100\n🚀 PUMP {p.get('score',0)}/100\n⚡ MOMENTUM {p.get('momentum_score',0)}/100\n🐋 HOLDER {p.get('holder_score',0)}/100\n👑 ELITE {e.get('score',0)}/100\n💎 GEM {g.get('score',0)}/100\n🔥 100X {x.get('score',0)}/100\n🎯 GÜVEN {a.get('confidence',0)}/100\n\n{d.get('emoji','⚪')} {d.get('decision','VERİ YETERSİZ')}\n↳ {d.get('reason','')}\n\n🎯 TRADE PLAN\nDurum: {pl.get('status','İZLE')}\n🟢 Giriş: {money(pl.get('entry_low'))} - {money(pl.get('entry_high'))} MC\n🛑 Stop: {money(pl.get('stop'))} MC\n🥉 TP1: {money(pl.get('tp1'))} MC\n🥈 TP2: {money(pl.get('tp2'))} MC\n🥇 TP3: {money(pl.get('tp3'))} MC\n\n📈 MC: {money(t.get('market_cap_usd'))}\n💧 Likidite: {money(t.get('liquidity_usd'))}\n📦 Hacim 5 dk: {money(t.get('volume_5m'))}\n🟢 Buy 5 dk: {t.get('buys_5m',0)}\n🔴 Sell 5 dk: {t.get('sells_5m',0)}\n\n⚠️ HunterElite karar destek aracıdır; garanti değildir.")[:4000]
def build_alert_report(t,a):
    r=a.get("rug") or {}; p=a.get("pump") or {}; e=a.get("elite") or {}; g=a.get("gem") or {}; x=a.get("x100") or {}; pl=a.get("trade_plan") or {}; c=str(t.get("address") or "").strip()
    return (f"🚨 HUNTER ALERT\n\n📋 CONTRACT\n{c}\n\n🪙 {t.get('name','Bilinmiyor')} ({t.get('symbol','?')})\n📈 MC: {money(t.get('market_cap_usd'))}\n💧 Likidite: {money(t.get('liquidity_usd'))}\n⏱ Yaş: {t.get('age_text','Bilinmiyor')}\n\n🛡 Rug: {r.get('score',0)}/100\n⚡ Momentum: {p.get('momentum_score',0)}/100\n🐋 Holder: {p.get('holder_score',0)}/100\n👑 Elite: {e.get('score',0)}/100\n💎 Gem: {g.get('score',0)}/100\n🔥 100X: {x.get('score',0)}/100\n\n🎯 {pl.get('status','İZLE')}\n🟢 Giriş: {money(pl.get('entry_low'))} - {money(pl.get('entry_high'))} MC\n🛑 Stop: {money(pl.get('stop'))} MC\n🥉 TP1: {money(pl.get('tp1'))} MC\n🥈 TP2: {money(pl.get('tp2'))} MC\n🥇 TP3: {money(pl.get('tp3'))} MC\n\n⚠️ Alarm güçlü aday filtresidir; kesin alım sinyali değildir.")[:4000]
